.github/workflows/build_test.yaml, src/utilities/build_libs.py
This pull request updates `build_libs.py` to ensure the METIS library is built with position-independent code as required for inclusion in shared libraries (eg. python interfaces). Fixes #10.
Additionally, this pull request made the following changes to the common code
- Add Ubuntu 22.04 variant to CI build
This pull request **does not** modify the any APIs or input files.
=> Update METIS build to ensure position-independent code

src/bin/thincurr_eig.F90, src/bin/thincurr_fr.F90, src/bin/thincurr_td.F90, src/tests/physics/test_thin_wall.py, src/utilities/CMakeLists.txt, src/utilities/oft_io.py
This pull request switches flux loop and jumper output in ThinCurr runs to use the OFT binary output history file format, including:
- Add support for converting binary output files to HDF5
- Update tests to use new format
This pull request **does not** modify any APIs or input files. This pull request **does** modify output files for ThinCurr runs.
=> Convert ThinCurr to use binary output format for history files

src/utilities/build_libs.py
This pull request fixe the CI build on macOS 13 (Ventura) by adding the linker fix in #12. As a consequence it should also fix all builds on macOS 13.
=> Add linker fix to build_libs for macOS 13 (Ventura), ref #12

src/physics/thin_wall.F90, src/tests/physics/test_thin_wall.py
This pull request corrects the resistivity of filament coils in ThinCurr to be consistent with SI units (`res_per_len` in [Ohm/m]), including:
- Update resistivity per length in regression tests
This pull request **does no**t modify any APIs. This pull request **does** modify the effect of the `res_per_len` attribute on `<coil_set>` or `<coil>` groups in a `<vcoils>` set in the `<thincurr>` group in XML input files.
=> ThinCurr: Correct resistivity units on filament coils to SI, fixes #30

.github/workflows/website.yaml
This pull request adds functionality to build the website for Open FUSION Toolkit for pull requests to support debugging of documentation changes.
=> Add website CI build with artifacts for pull requests

src/physics/grad_shaf_td.F90, src/python/OpenFUSIONToolkit/TokaMaker.py, src/python/wrappers/tokamaker_f.F90
This pull request adds support for multiple time-dependent solves in a single Python kernel, including:
- Add argument to include plasma contribution to preconditioner in time-dependent solve
- Refactor time-dependent code to improve storage and remove unused variables
This pull request **does not** modify any input files. This pull request **does** add new arguments (backwards compatible) to the `TokaMaker.setup_td()` function in the TokaMaker API.
=> TokaMaker: Add support for multiple time-dependent solves in a single Python kernel, fixes #42

.github/workflows/cd_nightly.yaml, .github/workflows/ci_build.yaml, .github/workflows/cov_build.yaml, .github/workflows/website.yaml, src/python/OpenFUSIONToolkit/Marklin.py, src/python/OpenFUSIONToolkit/TokaMaker.py
This pull request adds calls to [numpy.ascontiguousarray](https://numpy.org/doc/stable/reference/generated/numpy.ascontiguousarray.html) as needed to ensure proper memory layout of numpy arrays passed to compiled code through the Python wrapper.
=> Ensure proper memory layout for arrays passed through Python wrapper

src/physics/grad_shaf.F90, src/python/OpenFUSIONToolkit/TokaMaker.py, src/python/wrappers/tokamaker_f.F90
This pull request adds support for computing currents in conducting regions for quasi-static (from `psi`) cases, including:
- Add new function to compute current from `\psi` and `\Delta*`
- Separate current computation from `plot_eddy()` for other uses
- Add `psi` argument to `plot_eddy()` for quasi-static cases
This pull request **does not** modify any input files.
This pull request **does** add new arguments to the `TokaMaker` APIs in the `plot_eddy()` method. Additionally, new `get_delstar_curr ()`, `get_conductor_currents()`, and `get_conductor_source()` methods were added.
=> TokaMaker: Add functionality to compute currents in conducting regions

.github/workflows/website.yaml, src/docs/build_doc_versions.sh
This pull request adds functionality to build multiple versions of the documentation for the Open FUSION Toolkit website.
=> Update website action to include documentation from prior releases

src/physics/grad_shaf.F90, src/physics/grad_shaf_util.F90, src/python/OpenFUSIONToolkit/TokaMaker/_core.py, src/python/OpenFUSIONToolkit/TokaMaker/_interface.py, src/python/wrappers/tokamaker_f.F90
This pull request adds error handling to `OpenFUSIONToolkit.TokaMaker.TokaMaker.save_eqdsk()`
Additionally, the following changes to the core code were made:
- Update error reporting in `TokaMaker.get_q()` to report flux coordinate where tracing failed
This pull request **does not** modify any existing APIs or input file settings.
=> TokaMaker: Add error handling to `.save_eqdsk()` (failed tracing)

src/include/create_git_header.sh
This pull request fixes a compile error that can occur on certain Windows (WSL) machines due to carriage returns in git output.
=> Fix compile error on Windows (WSL) due to carriage returns in git output

src/CMakeLists.txt, src/utilities/build_libs.py
This pull request updates the `build_libs.py` to support explicit specification of the SDK path on macos, including:
- Support CMake based build of HDF5 in `build_libs.py`
- Update HDF5 version in `build_libs.py` to 1.14.2 and do not build high-level interface
- Cleanup and standardize CMake builds in `build_libs.py`
This pull request **does not** modify any APIs or input files. This pull request **does** add new `--macos_sdk_path`, `--hdf5_cmake_build` options to `build_libs.py`.
=> Add support for specifying the SDK path on macos

src/physics/grad_shaf.F90
This pull request improves performance of quasi-statice equilibrium solves using `.solve()` or `.vac_solve()` after calling `.set_psi_dt()` by only recomputing the matrix if the time step has changed.
=> TokaMaker: Only recompute operator for quasi-static solves if time step changes

.github/workflows/cov_build.yaml, src/CMakeLists.txt, src/base/oft_local_c.c, src/bin/thincurr_eig.F90, src/bin/thincurr_fr.F90, src/bin/thincurr_td.F90, src/cmake/FindOFT_UMFPACK.cmake, src/python/OpenFUSIONToolkit/util.py, src/tests/CMakeLists.txt, src/tests/physics/test_ThinCurr.py, src/tests/physics/test_TokaMaker.py
This pull request updates the coverage action workflow to fix issues and add reporting, including:
- Fix coverage detection for compiled code when using Python wrapper
- Enable matrix caching in ThinCurr tests and restructure test order to improve speed
Also make the following changes to the core code:
- Only search for PETSc in configure if path is given
- Fix comments in UMFPACK CMAKE find script
=> Update coverage action workflow

.github/workflows/cd_nightly.yaml
This pull request fixes GitHub actions CD workflows for macOS (x86) following deprecation of Monterey runners.
=> Move x86 CD build for macOS to Ventura following deprecation of Monterey on Github actions

src/physics/grad_shaf_util.F90, src/python/OpenFUSIONToolkit/TokaMaker/_core.py, src/python/wrappers/tokamaker_f.F90, src/utilities/build_libs.py
This pull request increases the accessible size of case field (`run_info` argument to `TokaMaker.save_eqdsk()`).
=> TokaMaker: Increase accessible size of case field in gEQDSK file I/O

src/base/oft_base.F90, src/physics/grad_shaf.F90, src/physics/grad_shaf_util.F90, src/python/OpenFUSIONToolkit/TokaMaker/_core.py, src/python/OpenFUSIONToolkit/TokaMaker/_interface.py, src/python/wrappers/tokamaker_f.F90
This pull request fixes the behavior of limiters with multiply connected plasma domains by locating all boundary loops of the plasma domain and tracking them (fixes #91).
**Note:** Only a single loop is supported in gEQDSK output so the longest loop with be used when calling `read_eqdsk()` and a warning will be printed.
Additionally, the following changes to core code were made:
- Remove processor ID number for debug/error information in single processor runs
=> TokaMaker: Fix behavior of limiters with multiply connected plasma domains

src/utilities/scripts/ThinCurr_compute_holes.py
This pull request fixes incorrect definition of closures when using `ThinCurr_compute_holes.py`. This bug has existed since the script was introduced in (a2ae861).
=> ThinCurr: Fix typos in closure definition in `ThinCurr_compute_holes.py`

src/grid/mesh_type.F90, src/physics/diagnostic.F90, src/physics/grad_shaf.F90, src/python/OpenFUSIONToolkit/TokaMaker/_core.py, src/python/OpenFUSIONToolkit/TokaMaker/_interface.py, src/python/wrappers/tokamaker_f.F90
This pull request adds support for specifying general current source terms in `vac_solve()` and `init_psi()`.
Additionally, the following changes were also made.
- TokaMaker: Respect cell curvature (always linear for now) in G-S integrals
- Fix OpenMP bug in `bscal_surf_int`
This pull request **does not** introduce breaking changes with any existing APIs or input files. This pull request **does** add new arguments to `OpenFUSIONToolkit.TokaMaker.TokaMaker.vac_solve()` and `OpenFUSIONToolkit.TokaMaker.TokaMaker.init_psi()`.
=> TokaMaker: Add support for general current source terms in `vac_solve` and `init_psi`

src/physics/grad_shaf_td.F90, src/python/OpenFUSIONToolkit/TokaMaker/_core.py
This pull request adds sorting to the result of eigenvalue solves within `eig_wall()` and `eig_td()` to ensure proper ordering of results. Additionally, checks were added to catch and report failure of the eigenvalue solver in these subroutines, which may produce erroneous results.
=> TokaMaker: Sort eigenvalues to ensure proper ordering in `eig_wall()` and `eig_td()`

.github/workflows/cd_nightly.yaml, .github/workflows/ci_build.yaml
This pull request fixes the CD build, following addition of an Intel oneAPI binary in b3242e5.
Additionally, this pull request adjust the CI/CD builds to share common GitHub action caches when possible.
=> Fix CD build following addition of oneAPI binary

src/physics/grad_shaf_util.F90
This pull request fixes a bug where the plasma resistivity profile was not being evaluated properly, leading to invalid results from `OpenFUSIONToolkit.TokaMaker.TokaMaker.calc_loopvoltage()` and `gs_calc_vloop`.
=> TokaMaker: Fix plasma resistivity handling for vloop, fixes #129

src/physics/grad_shaf_td.F90, src/python/OpenFUSIONToolkit/TokaMaker/_core.py, src/python/OpenFUSIONToolkit/TokaMaker/_interface.py, src/python/wrappers/tokamaker_f.F90
This pull request adds an optional damping term for linear calculations, designed to limit maximum growth rate and avoid or easily check cases that are erroneously identified as stable due to ideal-wall instability. Damping is applied by introducing a uniform resistivity (equal to `damping_scale*abs(omega)`) across the plasma region in the linearized operator.
This pull request **does not** introduce breaking changes for any existing APIs or input files.
=> TokaMaker: Add optional damping term for linear calculations to limit maximum growth rate

src/physics/grad_shaf_util.F90, src/python/OpenFUSIONToolkit/TokaMaker/_core.py, src/python/OpenFUSIONToolkit/TokaMaker/_interface.py, src/python/wrappers/tokamaker_f.F90, src/tests/physics/test_TokaMaker.py
This pull request adds support for specifying a non-zero LCFS pressure in `save_eqdsk()`, fixes #95
This pull request **does not** introduce breaking changes for any existing APIs or input files.
=> TokMaker: Add support for specifying a non-zero LCFS pressure in EQDSK output

src/base/oft_base.F90
This pull request fixes a compilation error with GCC 9 caused by pseudorandom seed size for test runs (fixes #138).
=> Fix compilation error with GCC 9

src/base/oft_io.F90, src/bin/marklin_eigs.F90, src/examples/MUG/Spheromak_heating/MUG_sph_heat.F90, src/examples/MUG/Spheromak_tilt/MUG_sph_tilt.F90, src/examples/example3.F90, src/examples/example4.F90, src/fem/fem_base.F90, src/fem/fem_composite.F90, src/physics/taylor.F90, src/physics/xmhd.F90, src/physics/xmhd_lag.F90, src/python/OpenFUSIONToolkit/Marklin/_core.py, src/python/OpenFUSIONToolkit/Marklin/_interface.py, src/python/wrappers/marklin_f.F90, src/tests/CMakeLists.txt, src/tests/base/CMakeLists.txt, src/tests/base/test_io.F90, src/tests/base/test_io.py, src/tests/oft_testing.py, src/tests/physics/test_Marklin.py, src/tests/physics/test_alfven.F90, src/tests/physics/test_alfven_lag.F90, src/tests/physics/test_sound.F90, src/tests/physics/test_sound_lag.F90, src/tests/physics/test_taylor.F90, src/tests/physics/test_taylor_inj.F90
This pull request removes the restriction of having only a single Marklin instance by encapsulating all required data/objects in the compiled code, including:
- The `save_rst` argument to `Marklin.compute()` is now deprecated in favor of a new `cache_file` argument, which enables specifying a specific file path for caching.
- Add regression test for concurrent Marklin instances
Additionally, the following changes were made to the core code:
- `hdf5_write` will now overwrite fields and issue a warning to avoid crashes with rewriting to files in a single Python script
- Improve error handling in FE `%vec_load()` implementations when fields are not present
- Add regression tests for HDF5 I/O operations
This pull request **does not** introduce breaking changes for any existing python APIs or …
=> Marklin: Remove restriction on single Marklin instance

src/grid/mesh_cube.F90, src/grid/multigrid.F90, src/lin_alg/native_la.F90, src/physics/oft_vector_inits.F90, src/tests/fem/test_lag.py, src/tests/physics/test_alfven.py, src/tests/physics/test_alfven_lag.py, src/tests/physics/test_sound.py, src/tests/physics/test_sound_lag.py
This pull request adds support for spatial packing for 2D square/rectangular meshes using the internal "cube" mesh construction functionality, including:
- Add support cell count specification for tetrahedra cube meshes (must be power of 2)
- Fix global indexing bug with multi-level periodic surface meshes
- Fix out of bounds bug in native sub-matrix setup
- Update MHD tests to use internal cube mesh
This pull request **does not** introduce changes for any existing APIs. This pull request **does** change the behavior of input files as the `ni` field in `cube_options` is now used for Tet meshes.
=> Add support for spatial packing in 2D square meshes

src/CMakeLists.txt, src/bin/CMakeLists.txt, src/bin/tokamaker_fit.F90, src/bin/tokamaker_gs.F90, src/bin/tokamaker_wall.F90, src/fem/lagrange_operators.F90, src/physics/axi_green.F90, src/physics/grad_shaf.F90, src/physics/grad_shaf_fit.F90, src/physics/grad_shaf_mercier.F90, src/physics/grad_shaf_profiles.F90, src/physics/grad_shaf_td.F90, src/physics/grad_shaf_util.F90, src/python/OpenFUSIONToolkit/TokaMaker/_interface.py, src/python/OpenFUSIONToolkit/TokaMaker/reconstruction.py, src/python/wrappers/tokamaker_f.F90, src/tests/physics/test_TokaMaker.py
This pull request deprecates the TokaMaker command line drivers and removes unused legacy code. Additionally, updates to documentation and fixes to undetected coverage testing are included.
This pull request does not introduce changes for any existing APIs or input files.
=> TokaMaker: Remove legacy code and deprecate command line drivers

.github/workflows/ci_build.yaml, .github/workflows/cov_build.yaml, .github/workflows/lint.yaml, src/CMakeLists.txt, src/base/oft_base.F90, src/base/oft_io.F90, src/base/oft_local_c.c, src/fem/fem_base.F90, src/fem/h1_basis.F90, src/fem/h1_operators.F90, src/fem/hcurl_basis.F90, src/fem/hcurl_grad_operators.F90, src/fem/hcurl_operators.F90, src/fem/lagrange_basis.F90, src/fem/lagrange_operators.F90, src/grid/bezier_cad.F90, src/grid/mesh_gmsh.F90, src/grid/mesh_native.F90, src/grid/tetmesh_type.F90, src/include/CMakeLists.txt, src/lin_alg/native_la.F90, src/physics/tracing.F90, src/utilities/build_libs.py, src/utilities/generate_stack.py
This pull request revives OFT's internal debug/profiling stack options that provides some level of cross-platform support for backtracing and profiling, including:
- Improve signal handling
- Add linting GitHub actions workflow to catch debug stack information
Additionally, the following changes to core code were made:
- Fix issue with 3rd party library builds for CMAKE >= 4.XX
This pull request **does not** introduce changes for any existing APIs or input files.
=> Revive OFT internal debug/profiling stack

src/physics/grad_shaf_util.F90
This pull request fixes a bug in TokaMaker's gEQDSK output, where malformed output may be generated (see #157)
=> TokaMaker: Fix malformed gEQDSK output caused by floating point exponent exceeding 2 digits

src/python/OpenFUSIONToolkit/TokaMaker/_core.py, src/python/OpenFUSIONToolkit/TokaMaker/reconstruction.py, src/python/OpenFUSIONToolkit/_core.py, src/python/wrappers/tokamaker_f.F90
This pull request adds catches for invalid global targets (negative values for quantities that must be positive), fixes #161. This is supported by the following changes:
- Add global environment functionality for dealing with float-valued disable flags
This pull request **does** introduce changes in the TokaMaker python API for `set_targets()` as to disable a target by passing an explicit value you must now use the new `OFT_env.float_disable_flag` value.
This pull request **does not** introduce changes for any existing input files.
=> TokaMaker: Catch invalid values for global targets (Ip, pax, etc.)

src/base/oft_io.F90, src/bin/marklin_eigs.F90, src/bin/thincurr_eig.F90, src/python/OpenFUSIONToolkit/Marklin/_core.py, src/python/OpenFUSIONToolkit/Marklin/_interface.py, src/python/OpenFUSIONToolkit/ThinCurr/_core.py, src/python/OpenFUSIONToolkit/ThinCurr/_interface.py, src/python/wrappers/marklin_f.F90, src/python/wrappers/thincurr_f.F90
This pull request add support for legacy HDF5 visualization files (as required by VisIt), by adding a new `legacy_hdf5` argument to `TokaMaker.setup_io()` and `ThinCurr.setup_io()`.
This pull request **does not** introduce breaking change to any existing APIs or input files.
=> Add support for legacy HDF5 visualization files

src/physics/grad_shaf.F90, src/python/OpenFUSIONToolkit/TokaMaker/_core.py, src/python/OpenFUSIONToolkit/TokaMaker/_interface.py, src/python/wrappers/tokamaker_f.F90, src/tests/physics/test_TokaMaker.py
This pull request adds improvements for TokaMaker calculations including:
- Add the ability to specify reference points for isoflux targets through new `ref_points` argument
- Add a new `TokaMaker.flux_integral()` method for computing the surface integral of a flux function
- Fix bug where isoflux/flux target solve may fail when no VSC is defined
- Fix bug where first flux or saddle target is skipped if no isoflux targets are set
This pull request **does not** introduce breaking changes in any existing APIs or input files.
=> TokaMaker: Improvements for double null and H-mode calculations

src/physics/thin_wall_solvers.F90, src/tests/physics/test_ThinCurr.py
This pull request modifies ThinCurr to always build jumpers for each hole in the mesh, without requiring explicit definition using a separate nodeset.
This pull request **does not** introduce breaking change to any existing APIs or input files.
=> ThinCurr: Always create jumpers for hole elements 

src/bin/thincurr_td.F90, src/physics/thin_wall.F90
This pull request fixes a bug in the setup of some jumpers in ThinCurr when the jumper does not include any boundary points. Additionally, the jumper setup process has been made more robust to capture corners and other edge cases.
=> ThinCurr: Fix bug with jumper setup when no boundary points are included

src/lin_alg/umfpack_bridge.c, src/python/OpenFUSIONToolkit/TokaMaker/_core.py, src/python/OpenFUSIONToolkit/TokaMaker/meshing.py
This pull request fixes adds tests to catch invalid region IDs within the mesh passed to TokaMaker.
=> TokaMaker: Add tests to catch invalid region IDs in mesh

src/python/OpenFUSIONToolkit/TokaMaker/_core.py, src/python/OpenFUSIONToolkit/TokaMaker/_interface.py, src/python/wrappers/tokamaker_f.F90, src/utilities/build_libs.py
This pull request reenables the `vacuum` option for TokaMaker's `solve()` method to allow vacuum solves with isoflux, saddle, etc. constraints.
This pull request **does not** introduce breaking changes for any existing python APIs or input files.
=> TokaMaker: Reenable vacuum solves through normal `.solve()` method

src/python/OpenFUSIONToolkit/TokaMaker/util.py
This pull request fixes bugs in `TokaMaker.util.read_mhdin` and `TokaMaker.util.read_kfile` introduced in a4a397c. These bugs were related to patches for the output of partially-working code in `OpenFUSIONToolkit.util.read_fortran_namelist` that was fixed in a4a397c, invalidating those patches.
=> TokaMaker: Fix bugs in EFIT readers introduced in a4a397c

src/python/OpenFUSIONToolkit/TokaMaker/_core.py, src/python/OpenFUSIONToolkit/TokaMaker/reconstruction.py
This pull request add code to check for and remove any remaining inverse constraints (eg. isoflux, saddles, etc.) from the underlying equilibrium solver that may conflict with the equilibrium reconstruction interface.
Additionally, this pull request makes the following changes:
- TokaMaker: Add sub-coil names to `TokaMaker.coil_sets` dictionary
=> TokaMaker: Remove equilibrium solver constraints if set before reconstruction
